# Generated by Django 2.2.6 on 2019-10-15 07:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('recap_id', models.IntegerField()),
                ('pacer_id', models.CharField(db_index=True, max_length=10)),
                ('date_filed', models.DateField(db_index=True)),
                ('date_terminated', models.DateField(blank=True, db_index=True, null=True)),
                ('date_blocked', models.DateField(blank=True, db_index=True, null=True)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('chapter', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recap_id', models.IntegerField()),
                ('date_filed', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recap_id', models.IntegerField()),
                ('pacer_id', models.CharField(db_index=True, max_length=10)),
                ('doc_type', models.CharField(max_length=10)),
                ('is_sealed', models.BooleanField()),
                ('is_available', models.BooleanField()),
                ('file_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=1000000, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('docket_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.DocketEntry')),
            ],
        ),
    ]
