# Generated by Django 2.2.6 on 2019-10-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docketentry',
            name='data',
        ),
        migrations.RemoveField(
            model_name='document',
            name='data',
        ),
    ]
