# Generated by Django 2.2.6 on 2019-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20191015_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='pacer_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='pacer_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
