# Generated by Django 2.2.6 on 2019-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20191015_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketentry',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
