# Generated by Django 2.2.6 on 2019-10-15 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20191015_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_created',
            field=models.DateField(db_index=True, default=datetime.datetime(2019, 10, 15, 10, 34, 8, 911408)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docketentry',
            name='date_created',
            field=models.DateField(db_index=True, default=datetime.datetime(2019, 10, 15, 10, 34, 14, 927044)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='date_filed',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='date_filed',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
